name: Tests

on: [push, pull_request]

jobs:
  build-posix:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    # - name: Set up Python 3.10
    #   uses: actions/setup-python@v3
    #   with:
    #     python-version: '3.10'
    - if: matrix.os == 'ubuntu-latest'
      name: Install dependencies
      run: |
        sudo apt-get update
    - name: Use Mamba to create env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: eeldev
        create-args: >-
          python=3.10
          libcblas
          numpy>=1.20
          wxpython>=4.1.0
          rpy2
          r-car
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'
    - name: Build eelbrain
      run: pip install -e .[all]
      shell: bash -el {0}
    - if: matrix.os == 'ubuntu-latest'
      name: Test without GUI
      shell: bash -el {0}
      env:
        DISPLAY: :99
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        pytest eelbrain --cov --cov-report=xml --no-gui
    - if: matrix.os == 'macos-latest'
      name: Test with GUIs and code-cov
      shell: bash -el {0}
      run: |
        pytest eelbrain --cov --cov-report=xml
    - if: matrix.os == 'macos-latest'
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
